### ISSUE TITLE
Spark Integration Error: No module named bs4

### ISSUE THREAD

**Issue by paulcichonski** [DataDog/docker-dd-agent#131]
Not sure if this belongs here or in the `dd-agent` repo itself.

*_Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) *_

Working from `:latest`:

```
===================
Collector (v 5.9.0)
===================

  Status date: 2016-09-29 15:33:28 (10s ago)
  Pid: 194
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0075 s
    System UTC time: 2016-09-29 15:33:39.421288

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    socket-hostname: 3cdce13865ff
    hostname: 3cdce13865ff
    socket-fqdn: 3cdce13865ff

  Checks
  ======

    ntp
    ---
      - instance #0 [OK]
      - Collected 1 metric, 0 events & 2 service checks

    disk
    ----
      - instance #0 [OK]
      - Collected 40 metrics, 0 events & 1 service check

    docker_daemon
    -------------
      - instance #0 [OK]
      - Collected 19 metrics, 4 events & 2 service checks

    zk
    --
      - instance #0 [OK]
      - Collected 23 metrics, 0 events & 2 service checks

    spark
    -----
      - initialize check class [ERROR]: ImportError('No module named bs4',)

  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.9.0)
===================

  Status date: 2016-09-29 15:33:30 (9s ago)
  Pid: 31
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 3
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.9.0)
===================

  Status date: 2016-09-29 15:33:38 (0s ago)
  Pid: 33
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 12
  Transactions received: 4
  Transactions flushed: 4
  Transactions rejected: 0
```

**Additional environment details (Operating System, Cloud provider, etc):**
My `spark.yaml` config:

```
init_config:

instances:
  #
  # The Spark check can retrieve metrics from Standalone Spark and YARN. Both
  # methods require the spark_url to be configured.
  #
  # For Spark Standalone, `spark_url` must be set to the Spark master's web
  # UI. This is http://localhost:8080 by default.
  #
  # For YARN, `spark_url` must be set to YARN's resource manager address. The
  # ResourceManager hostname can be found in the yarn-site.xml conf file
  # under the property yarn.resourcemanager.address The ResourceManager port
  # can be found in the yarn-site.xml conf file under the property
  # yarn.resourcemanager.webapp.address. This is http://localhost:8088 by default
  #
  # The use of `resourcemanager_uri` has been deprecated, but is still functional.
  - spark_url: http://sparkmaster:8080

    # To enable monitoring of a Standalone Spark cluster, the spark cluster
    # mode must be set. Uncomment the cluster mode that applies.
    # spark_cluster_mode: spark_yarn_mode
    spark_cluster_mode: spark_standalone_mode

    # A Required friendly name for the cluster.
    cluster_name: MySparkCluster

    # Optional tags to be applied to every emitted metric.
    # tags:
    #   - key:value
    #   - instance:production

```

**Additional information you deem important (e.g. issue happens only occasionally):**
Simple workaround for now is:

```
FROM datadog/docker-dd-agent:latest
RUN /opt/datadog-agent/embedded/bin/pip install BeautifulSoup4

```
