### ISSUE TITLE
**Many fails when sending datadog metrics when using image datadog/docker-dd-agent:latest-alpine

### ISSUE THREAD

**Issue by dror-ventura** [DataDog/docker-dd-agent#162]
```
{"message":"getaddrinfo EAI_AGAIN","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN
at Object.exports._errnoException (util.js:1026:11)
at errnoException (dns.js:33:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)","code":"EAI_AGAIN"},"msg":"Failed sending data to datadog agent","time":"2017-01-29T12:26:38.375Z","v":0}
```
**NOTE: when using image datadog/docker-dd-agent:latest no errors such as the error above**

**Comment by hkaj** [comment]
Hi @dror-ventura 
thanks for the feedback. Can you give us more details about your setup? Maybe how you run the agent container, and a snippet that gives this failure message.

Thanks

**Comment by dror-ventura** [comment]
from my docker-compose:
```
dd-agent:
    image: datadog/docker-dd-agent:latest-alpine

    environment:
      - API_KEY=<MY API KEY>

    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /proc/mounts:/host/proc/mounts:ro
       - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

```
I tried it in my staging environment for some time and unfortunately I don't have a specific call stack of my application when the errors occur,
I can say that I'm using mostly increment metrics, and error events while using node-statsd library.

i'm running datadog/docker-dd-agent:latest on production along with the same code and configuration and i haven't received such errors
