### ISSUE TITLE
Document Container Networking using User-Defined Networks

### ISSUE THREAD

**Issue by eedwardsdisco** [DataDog/docker-dd-agent#172]
As per Docker's pages on using [--link](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) and the new [user-defined networks](https://docs.docker.com/engine/userguide/networking/), using links is deprecated and may be removed in the future.

It sounds like user-defined networks have a limitation that linking for dd-agent\dogstatsd relies on:

>One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

Since the alternative sounds complicated, an officially vetted list of instructions on how to properly expose dogstatsd\dd-agent to other containers without using the legacy `--link` option, would be useful!

**Comment by tylermann** [comment]
+1 to updating the documentation for getting statsd working without using link, as you can't use link at all for docker swarm afaik and the localhost approach also likely won't work out of the box for people using docker swarm. took me a while to figure out how to get things working (although I was also kind of new to docker swarm and overlay networks.) I'll leave this example config here that I got working but not sure if this is the best way.

1. make sure you update your containers sending metrics to point to host 'dd-agent' or whatever you named your docker agent container.
2. Make sure your other containers are on the same overlay network as the docker agent
3. Make sure your docker agent has has the `NON_LOCAL_TRAFFIC` env variable set (see example config below.

```
version: '3'
services:
    web:
        image: <your container image that sends metrics >
        networks:
            - default
        ports:
            - "80:80"
            - "443:443"
    dd-agent:
        image: datadog/docker-dd-agent:latest
        deploy:
            mode: global
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
        networks:
            - default
        environment:
            API_KEY: <your datadog Key>
            SD_BACKEND: docker
            NON_LOCAL_TRAFFIC: 'True'
networks:
    default:
```
