### ISSUE TITLE
jmx: sane sd default & integration w/k8s annotations

### ISSUE THREAD

**Issue by flah00** [DataDog/docker-dd-agent#197]
I'm using `datadog/docker-dd-agent:latest-jmx`, with k8s 1.5.5. I'm fascinated by the support for annotations. I would love to mark my pods with annotations, instead of updating the `docker_images` key, for my jmx configuration. But my configuration is pretty hairy, because I like collecting metrics for GC, regardless of the GC i'm using. 

I can't put the configuration into etcd, because we're using [kube-aws](https://github.com/kubernetes-incubator/kube-aws), which secures etcd with TLS. It's my understanding that TLS isn't currently supported by datadog's service discovery. 

If there's a better way, I'm open to it, but right now, it seems like the best options are 

1. supporting etcd TLS
1. annotations which point to SD configmaps
1. some other option I'm unaware of or can't conceive 

Here's the jmx portion of my datadog configuration, based on the `stable/datadog` helm chart.

```yaml
    jmx.yaml: |-
      ---
      docker_images:
        - hub
        - jenkins
        - jnlp-slave
        - node-chrome
        - node-chrome-debug
        - node-firefox
        - node-firefox-debug
      instances:
      - conf:
        - include:
            domain: java.lang
            bean: java.lang:type=OperatingSystem
        - include:
            domain: java.lang
            bean: java.lang:type=Memory
        - include:
            domain: java.lang
            bean: java.lang:type=Threading
        - include:
            domain: java.lang
            type: MemoryPool
            name: CMS Old Gen
            attribute:
            - Usage
        - include:
            domain: java.lang
            type: MemoryPool
            name: CMS Perm Gen
            attribute:
            - Usage
        - include:
            domain: java.lang
            type: MemoryPool
            name: Par Eden Space
            attribute:
            - Usage
        - include:
            domain: java.lang
            type: MemoryPool
            name: Par Survivor Space
            attribute:
            - Usage
        - include:
            domain: java.lang
            type: GarbageCollector
            name: Copy
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.minor_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.minor_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: PS Scavenge
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.minor_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.minor_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: ParNew
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.minor_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.minor_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: G1 Young Generation
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.minor_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.minor_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: MarkSweepCompact
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.major_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.major_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: PS MarkSweep
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.major_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.major_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: ConcurrentMarkSweep
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.major_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.major_collection_time
        - include:
            domain: java.lang
            type: GarbageCollector
            name: G1 Old Generation
            attribute:
              CollectionCount:
                metric_type: counter
                alias: jmx.gc.major_collection_count
              CollectionTime:
                metric_type: counter
                alias: jmx.gc.major_collection_time
        - include:
            domain: java.nio
        host: "%%host%%"
        port: 4000
        name: "%%host%%"
      init_config:
```
