### ISSUE TITLE
k8s: Read env from KUBERNETES_SERVICE_*

### ISSUE THREAD

**Issue by pierreozoux** [DataDog/docker-dd-agent#201]
I deployed a cluster on amazon, using kops 1.6, and deployed dd-agent using the [helm chart](https://github.com/kubernetes/charts/tree/master/stable/datadog).

It didn't read: `KUBERNETES_SERVICE_HOST`, but preferred the hostname.
I managed to hard [write it](https://github.com/DataDog/dd-agent/blob/master/utils/kubernetes/kubeutil.py), and it was working.

I can see in the code that it doesn't read from `KUBERNETES_SERVICE_PORT` but instead try to be smart between 2 port (10255 and 10250). (Maybe a new behaviour of k8s?)

It didn't manage to read the `ca_cert`. I had to hard write it also.

And finally, I didn't manage to connect it to cadvisor. For dd-agent defense, I also have no idea where to try :/

If you have any idea on the last one, it would be amazing :)

**Comment by pierreozoux** [comment]
I solved my issue by actually just using:

```
      hostNetwork: true
```

```
{{- if .Values.datadog.apiKey }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}
    spec:
      hostNetwork: true
      tolerations:
      - operator: "Exists"
      containers:
      - name: {{ .Chart.Name }}
```
