### ISSUE TITLE
Resource limit for docker dd agent in kubernetes

### ISSUE THREAD

**Issue by ravibhure** [DataDog/docker-dd-agent#209]
docker-dd-agent not specified the resource limits in [dd-agent.yaml](https://app.datadoghq.com/account/settings#agent/kubernetes) file which causes kube cluster down to over usage of resources by dd-agent 

Below is just an example, needs fix resource limit for docker-dd-agent in kubernetes cluster environments.

```
## dd-agent resource requests and limits
resources:  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 512Mi
```
