### ISSUE TITLE
[Kubernetes] No configmap created with leader_candidate: true if namespaces are not defined

### ISSUE THREAD

**Issue by lorantonodi** [DataDog/docker-dd-agent#237]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
kubectl exec -it  dd-agent-3dmzk /etc/init.d/datadog-agent status --namespace=kube-system                                                                                            ✔  2714  15:16:37
Warning: Known bug in Linux Kernel 3.18+ causes 'status' to fail.
Calling 'info', instead...
2017-09-13 14:16:49,337 | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Collector (v 5.17.0)
====================

  Status date: 2017-09-13 14:16:31 (18s ago)
  Pid: 24
  Platform: Linux-4.4.78-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: -0.0044 s
    System UTC time: 2017-09-13 14:16:49.472537

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-172-20-56-149.eu-west-1.compute.internal
    local-ipv4: 172.20.56.149
    socket-hostname: dd-agent-3dmzk
    hostname: i-03f748ace24133fb6
    local-hostname: ip-172-20-56-149.eu-west-1.compute.internal
    instance-id: i-03f748ace24133fb6
    socket-fqdn: dd-agent-3dmzk

  Checks
  ======

    ntp (5.17.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (5.17.0)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks

    kubernetes (5.17.0)
    -------------------
      - instance #0 [OK]
      - Collected 133 metrics, 0 events & 3 service checks

    docker_daemon (5.17.0)
    ----------------------
      - instance #0 [OK]
      - Collected 90 metrics, 0 events & 1 service check


  Emitters
  ========

    - http_emitter [OK]

2017-09-13 14:16:51,531 | WARNING | dd.dogstatsd | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Dogstatsd (v 5.17.0)
====================

  Status date: 2017-09-13 14:16:44 (6s ago)
  Pid: 21
  Platform: Linux-4.4.78-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 152
  Packet Count: 1732
  Packets per second: 1.0
  Metric count: 10
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.17.0)
====================

  Status date: 2017-09-13 14:16:51 (1s ago)
  Pid: 17
  Platform: Linux-4.4.78-k8s-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 1618 bytes
  Queue Length: 1
  Flush Count: 502
  Transactions received: 387
  Transactions flushed: 386
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.17.0)
======================

  Pid: 16
  Uptime: 1559 seconds
  Mem alloc: 845744 bytes

  Hostname: dd-agent-3dmzk
  Receiver: 0.0.0.0:8126
  API Endpoint: https://trace.agent.datadoghq.com

  Bytes sent (1 min): 0
  Traces sent (1 min): 0
  Stats sent (1 min): 0

```

**Additional environment details (Operating System, Cloud provider, etc):**
Debian GNU/Linux 8 (jessie)   4.4.78-k8s, Kubernetes 1.7.4, AWS

**Steps to reproduce the issue:**
1. Deploying the following datadog daemonset to the k8s cluster:
``` 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
    spec:
      containers:
      - image: datadog/docker-dd-agent:latest
        imagePullPolicy: Always
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: API_KEY
            value: ********
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
          - name: KUBERNETES_LEADER_CANDIDATE
            value: "True"
          - name: KUBERNETES_LEADER_LEASE_DURATION
            value: "60"
          - name: KUBERNETES_NAMESPACE_NAME_REGEX
            value: "'.*'"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
```
2. Wait 5 minutes, then
```
kubectl get configmaps --namespace kube-system
```

**Describe the results you received:**
No  datadog-leader-elector configmap present, no kubernetes events showing up in Datadog events

**Describe the results you expected:**
NAMESPACE     NAME                                 DATA      AGE
kube-system   datadog-leader-elector               0         5m

Kubernetes events starts to show up in Datadog

**Additional information you deem important (e.g. issue happens only occasionally):**
If I override the /etc/dd-config/conf.d/kubernetes.yaml.example in the datadog/docker-dd-agent:latest config

Dockerfile:
```
FROM datadog/docker-dd-agent:latest

COPY ./kubernetes.yaml.example /etc/dd-agent/conf.d/kubernetes.yaml.example
```

kubernetes.yaml.example diff:
```
--- /Users/lonodi/dev/work/kubernetes.yaml.example.orig	Wed Sep 13 15:26:03 2017
+++ /Users/lonodi/dev/work/kubernetes.yaml.example	Wed Sep 13 14:46:03 2017
@@ -113,8 +113,8 @@
   # The namespaces for which events should be collected.
   # If not modified, the 'default' namespace will be used.
   #
-  # namespaces:
-  #  - default
+   namespaces:
+    - default
 
   # The regexp used to select namespaces for which events should be collected.
   # The matched namespaces will be added to the "namespaces" list.
```
And recreate the Daemonset, it start to work, Configmap is created and events are showing up for all namespaces.
