### ISSUE TITLE
docker_daemon.yaml "exclude" option doesn't exclude

### ISSUE THREAD

**Issue by sarkistlt** [DataDog/docker-dd-agent#276]
Hi, I'm using custom image to copy config file, this is Dockerfile:
```yml
FROM datadog/docker-dd-agent:latest
COPY ./docker_daemon.yaml /etc/dd-agent/conf.d/docker_daemon.yaml
```
and my `docker_daemon.yaml` looks like:

```yml
init_config:
  docker_root: /host

instances:
    url: "unix://var/run/docker.sock"
    exclude: ["dockercloud/cleanup", "dockercloud/logrotate", "dockercloud/network-daemon", "dockercloud/ntpd", "weaveworks/plugin", "weaveworks/weave", "weaveworks/weaveexec", "weaveworks/*", "dockercloud/*"]
    include: []
```

But it's still keep tracking all those images from `exclude` array.
