### ISSUE TITLE
Instance check skipped

### ISSUE THREAD

**Issue by xueshanf** [DataDog/docker-dd-agent#28]
What could cause this error in collector.log:

```
2015-06-08 19:17:57 UTC | ERROR | dd.collector | checks.http_check(network_checks.py:125) | Instance: CI  skipped because it's already running
2015-06-08 19:18:24 UTC | CRITICAL | dd.collector | checks.http_check(network_checks.py:214) | Restarting Pool. One check is stuck:  CI
```

Here is the relevant info:

Image: datadog/docker-dd-agent:latest

```
root@anchorage-admiral:/# dd-agent info
===================
Collector (v 5.3.0)
===================

  Status date: 2015-06-08 19:11:52 (19s ago)
  Pid: 16
  Platform: Linux-4.0.1-x86_64-with-debian-7.8
  Python Version: 2.7.9
  Logs: <stderr>, /var/log/datadog/collector.log

....
http_check
    ----------
      - instance #0 [WARNING]
          Warning: Using events for service checks is deprecated in favor of monitors and will be removed in future versions of the Datadog Agent.
          Warning: Using events for service checks is deprecated in favor of monitors and will be removed in future versions of the Datadog Agent.
          Warning: Using events for service checks is deprecated in favor of monitors and will be removed in future versions of the Datadog Agent.
          Warning: Using events for service checks is deprecated in favor of monitors and will be removed in future versions of the Datadog Agent.
          Warning: Using events for service checks is deprecated in favor of monitors and will be removed in future versions of the Datadog Agent.
      - instance #1 [OK]
      - instance #2 [OK]
      - instance #3 [OK]
      - instance #4 [OK]
      - instance #5 [OK]
      - instance #6 [OK]
```

The checks that causing ERROR are https checks in conf.d/tcp_check.yaml, in fact, all https checks configured this way are skipped:

```yaml
-   name: CI
        url: https://ci.example.com
        timeout: 10
        window: 5
        threshold:  3
        tags:
            - url:https://ci.example.com
            - env:anchorage
        content_match: Authentication required
        http_response_status_code: 403
        include_content: true
```

I am trying to do a check based on http response code and content match here.
What I am doing wrong? I looked the network_check source code but could not figure out why the https check was skipped.
