### ISSUE TITLE
DD_HISTOGRAM_PERCENTILES: how to disable all percentiles?

### ISSUE THREAD

**Issue by andreaippo** [DataDog/docker-dd-agent#380]
Hi,

I'm looking for ways to disable the default 0.95 percentile.

Which value am I supposed to provide?

Here's a portion of my `compose` file. Thanks in advance!

```yml
  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: <my_name>
    pid: host
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8126:8126"
      - "8125:8125/udp"
    networks:
      -  <my_net>
    environment:
      - DD_API_KEY=<hidden>
      - DD_SITE=datadoghq.eu
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_OTLP_CONFIG_METRICS_RESOURCE_ATTRIBUTES_AS_TAGS=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=<my_host>
      - DD_HISTOGRAM_PERCENTILES=???
    volumes:
      # comment docker.sock line if using podman
      # - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
```
