### ISSUE TITLE
Tags set via environment not showing up

### ISSUE THREAD

**Issue by volker48** [DataDog/docker-dd-agent#65]
I'm not seeing any of the tags I set via environment variables ending up in my datadog metrics.

```yml
    dogstatsd:
        image: datadog/docker-dd-agent:11.0.563
        command: dogstatsd
        environment:
          API_KEY: 'redacted'
          TAGS: 'environment:development'
```

I'm using docker-compose and my metrics show up in Datadog, but not this tag I'm setting.
